name: "metro_tokyo"
version: "1.0.0"

profile: "metro_tokyo"

model-paths: ["models"]
macro-paths: ["macros", "shared/macros"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  metro_tokyo:
    +database: metro_tokyo
    +materialized: view
    catalog:
      raw:
        +materialized: table
      stg:
        +materialized: table
      mart:
        +materialized: table
    ods:
      raw:
        +materialized: table
      stg:
        +materialized: table
      mart:
        +materialized: table
    childcare:
      raw:
        +materialized: table
      stg:
        +materialized: table
      mart:
        +materialized: table
    stats:
      raw:
        +materialized: table
      stg:
        +materialized: table
      mart:
        +materialized: table
