name: Sync

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
  workflow_dispatch:

concurrency:
  group: sync
  cancel-in-progress: false

jobs:
  sync:
    uses: queria-io/dataset-shared/.github/workflows/sync.yml@main
    with:
      dataset_name: metro_tokyo
      s3_bucket: ${{ vars.S3_BUCKET }}
    secrets: inherit
